version: "3.9"
services:
  nparse-locserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8424:8424"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        compress: "true"
